package com.FujitsuFoodDeliveryAPI.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Data
@Entity
public class DeliveryFee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String city;
    private String vehicleType;
    private double temperature;
    private double windSpeed;
    private String weatherPhenomenon;
    private double fee; // This field will store the calculated delivery fee

    // Constructors, getters, and setters are generated by Lombok

    // Method to calculate the delivery fee based on input parameters
    public void calculateDeliveryFee() {
        double baseFee = getBaseFee(this.city, this.vehicleType);
        double temperatureFee = getTemperatureFee(this.temperature);
        double windSpeedFee = getWindSpeedFee(this.vehicleType, this.windSpeed);
        double weatherPhenomenonFee = getWeatherPhenomenonFee(this.weatherPhenomenon);

        this.fee = baseFee + temperatureFee + windSpeedFee + weatherPhenomenonFee;
    }

    // Method to calculate the delivery fee based on input parameters
    public double calculateDeliveryFee(String city, String vehicleType, double temperature, double windSpeed, String weatherPhenomenon) {
        double baseFee = getBaseFee(city, vehicleType);
        double temperatureFee = getTemperatureFee(temperature);
        double windSpeedFee = getWindSpeedFee(vehicleType, windSpeed);
        double weatherPhenomenonFee = getWeatherPhenomenonFee(weatherPhenomenon);

        return baseFee + temperatureFee + windSpeedFee + weatherPhenomenonFee;
    }

    private double getBaseFee(String city, String vehicleType) {
        // Define base fees for each city and vehicle type
        switch (city) {
            case "Tallinn":
                return vehicleType.equals("Car") ? 4.0 : vehicleType.equals("Scooter") ? 3.5 : 3.0;
            case "Tartu":
                return vehicleType.equals("Car") ? 3.5 : vehicleType.equals("Scooter") ? 3.0 : 2.5;
            case "Pärnu":
                return vehicleType.equals("Car") ? 3.0 : vehicleType.equals("Scooter") ? 2.5 : 2.0;
            default:
                throw new IllegalArgumentException("Unknown city");
        }
    }

    private double getTemperatureFee(double temperature) {
        // Extra fee for temperature
        if (temperature < -10.0) {
            return 1.0;
        } else if (temperature < 0.0) {
            return 0.5;
        }
        return 0.0;
    }

    private double getWindSpeedFee(String vehicleType, double windSpeed) {
        // Extra fee for wind speed (only for Bike)
        if ("Bike".equals(vehicleType) && windSpeed > 20.0) {
            throw new IllegalArgumentException("Usage of selected vehicle type is forbidden");
        }
        return windSpeed > 10.0 ? 0.5 : 0.0;
    }

    private double getWeatherPhenomenonFee(String weatherPhenomenon) {
        // Extra fee for weather phenomenon
        switch (weatherPhenomenon) {
            case "Heavy snow shower":
            case "Light snow shower":
            case "Moderate snow shower":
            case "Light sleet":
            case "Moderate sleet":
            case "Light snowfall":
            case "Moderate snowfall":
            case "Heavy snowfall":
            case "Blowing snow":
            case "Drifting snow":
                return 1.0;
            case "Light shower":
            case "Moderate shower":
            case "Heavy shower":
            case "Light rain":
            case "Moderate rain":
            case "Heavy rain":
                return 0.5;
            default:
                return 0.0;
        }
    }
}
